don't test on 36 yet
java.lang.UnsupportedOperationException: Failed to create a Robolectric sandbox: Android SDK 36 requires Java 21 (have Java 17)
	at org.robolectric.plugins.DefaultSdkProvider$DefaultSdk.verifySupportedSdk(DefaultSdkProvider.java:170)
	at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:262)
	at org.robolectric.RobolectricTestRunner.getSandbox(RobolectricTestRunner.java:64)
	at org.robolectric.internal.SandboxTestRunner.sandboxGroupingClassBlock(SandboxTestRunner.java:140)
	at org.robolectric.internal.SandboxTestRunner.classBlock(SandboxTestRunner.java:119)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:412)
	at org.robolectric.RobolectricTestRunner.run(RobolectricTestRunner.java:142)