Move to Roboletric to avoid reflection.
java.lang.IllegalAccessException: static final field has no write access: android.os.Build$VERSION.SDK_INT/int/putStatic, from class java.lang.Object (module java.base)